import { createContext, useContext, useEffect, useState } from 'react';

export type Locale = 'es' | 'en';
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string; };

const copy: Record<Locale, Record<string, string>> = {
  es: {
    'nav.product':'Producto','nav.download':'Descargas','nav.pricing':'Pricing','nav.contact':'Contacto','nav.login':'Iniciar sesión','nav.logout':'Cerrar sesión','nav.downloadCta':'Descargar','nav.language':'Idioma',
    'hero.eyebrow':'CISPAR SECURITY OPERATIONS','hero.title':'Tu SOC autónomo, con visibilidad real.','hero.body':'CISPAR reúne eventos, análisis y playbooks para operar la seguridad desde tu propia infraestructura.','hero.download':'Descargar CISPAR','hero.sales':'Hablar con el equipo','hero.note':'Compatible con macOS, Windows y Linux. Despliegue local con Docker.','hero.system':'Sistema local','hero.posture':'POSTURA ACTUAL','hero.monitoring':'Entorno supervisado','hero.sources':'Fuentes','hero.connected':'Conectadas','hero.events':'Eventos','hero.realtime':'En tiempo real','hero.response':'Respuesta','hero.playbook':'Por playbook','hero.event':'Actividad de autenticación revisada','hero.now':'ahora',
    'product.eyebrow':'OPERACIÓN CON CONTEXTO','product.title':'Tecnología que entiende antes de responder.','product.body':'Combina ingesta de eventos, investigación y playbooks en una experiencia pensada para equipos de seguridad.','product.oneTitle':'Ingesta y contexto','product.oneBody':'Centraliza eventos y conserva el contexto necesario para investigarlos.','product.twoTitle':'Respuesta trazable','product.twoBody':'Organiza acciones por playbook y deja una bitácora por incidente.','product.threeTitle':'Despliegue propio','product.threeBody':'El SIEM se ejecuta en el entorno que controlas.','product.installEyebrow':'EMPIEZA EN TU ENTORNO','product.installTitle':'Elige un instalador y completa la configuración guiada.','product.install':'Ver descargas',
    'tech.eyebrow':'VISIBILIDAD · INVESTIGACIÓN · RESPUESTA','tech.title':'Un flujo técnico, desde la señal hasta la decisión.','tech.body':'CISPAR organiza lo que ocurre en tu entorno para que cada paso pueda revisarse y operarse con contexto.','tech.detect':'Detectar','tech.detectBody':'Recibe, normaliza y prioriza actividad de seguridad.','tech.investigate':'Investigar','tech.investigateBody':'Relaciona evidencia y eventos para dar contexto al incidente.','tech.respond':'Responder','tech.respondBody':'Ejecuta playbooks definidos y conserva la trazabilidad.','tech.terminal':'CISPAR / incident-response','tech.live':'EN EJECUCIÓN','tech.line1':'[ingesta] eventos de seguridad recibidos','tech.line2':'[análisis] contexto de autenticación preparado','tech.line3':'[playbook] revisión requerida antes de contener','tech.line4':'[registro] incidente documentado',
    'download.eyebrow':'DESCARGAS','download.title':'Instala CISPAR en tu entorno.','download.body':'Selecciona tu plataforma. Cada release publicada incluye SHA-256 para verificar la descarga.','download.recommended':'RECOMENDADO PARA ESTE EQUIPO','download.pending':'Próxima release','download.checksum':'Pendiente de publicación','download.button':'Instalador en preparación','download.after':'DESPUÉS DE DESCARGAR','download.afterTitle':'El instalador prepara Docker y abre la configuración local.','download.step1':'Ejecuta el instalador correspondiente a tu sistema.','download.step2':'Inicia sesión cuando CISPAR solicite autorización.','download.step3':'Completa la configuración guiada en el navegador.','download.help':'¿Necesitas ayuda con arquitectura, requisitos o una instalación empresarial?','download.contact':'Contactar al equipo',
    'pricing.eyebrow':'PLANES','pricing.title':'Elige el alcance adecuado para tu operación.','pricing.body':'El precio y los límites se definen según el entorno, fuentes y requisitos de despliegue.','pricing.starter':'Starter','pricing.starterBody':'Para validar CISPAR en un entorno inicial.','pricing.enterprise':'Enterprise','pricing.enterpriseBody':'Para equipos con mayor volumen, integración o requisitos de despliegue.','pricing.quote':'Propuesta a medida','pricing.access':'Solicitar acceso','pricing.sales':'Hablar con ventas','pricing.note':'Para varias sedes, integraciones o requisitos específicos, cuéntanos sobre tu entorno.',
    'contact.eyebrow':'CONTACTO','contact.title':'Hablemos de tu entorno.','contact.body':'Solicita una demo, propuesta o ayuda para planear la instalación.','contact.tipTitle':'Para una mejor respuesta','contact.tip':'Incluye tipo de entorno, fuentes aproximadas y requisitos de integración.','contact.type':'Tipo de solicitud','contact.name':'Nombre','contact.company':'Empresa','contact.email':'Correo de trabajo','contact.environment':'Entorno','contact.message':'¿Qué necesitas?','contact.placeholder':'Describe brevemente el entorno y lo que buscas.','contact.send':'Preparar solicitud','contact.sent':'Se abrió tu cliente de correo con la solicitud preparada. Si no se abrió, escribe a sales@cispar.io.','contact.demo':'Demo','contact.quote':'Cotización','contact.install':'Instalación','footer.tagline':'Operaciones de seguridad instaladas en tu entorno.'
  },
  en: {
    'nav.product':'Product','nav.download':'Downloads','nav.pricing':'Pricing','nav.contact':'Contact','nav.login':'Sign in','nav.logout':'Sign out','nav.downloadCta':'Download','nav.language':'Language',
    'hero.eyebrow':'CISPAR SECURITY OPERATIONS','hero.title':'Your autonomous SOC, with real visibility.','hero.body':'CISPAR brings events, analysis, and playbooks together to operate security from your own infrastructure.','hero.download':'Download CISPAR','hero.sales':'Talk to the team','hero.note':'Compatible with macOS, Windows, and Linux. Local Docker deployment.','hero.system':'Local system','hero.posture':'CURRENT POSTURE','hero.monitoring':'Monitored environment','hero.sources':'Sources','hero.connected':'Connected','hero.events':'Events','hero.realtime':'Real time','hero.response':'Response','hero.playbook':'By playbook','hero.event':'Authentication activity reviewed','hero.now':'now',
    'product.eyebrow':'OPERATIONS WITH CONTEXT','product.title':'Technology that understands before it responds.','product.body':'Combines event intake, investigation, and playbooks in an experience built for security teams.','product.oneTitle':'Ingestion and context','product.oneBody':'Centralize events and retain the context needed to investigate them.','product.twoTitle':'Traceable response','product.twoBody':'Organize actions through playbooks and leave an audit trail for every incident.','product.threeTitle':'Your deployment','product.threeBody':'The SIEM runs in the environment you control.','product.installEyebrow':'START IN YOUR ENVIRONMENT','product.installTitle':'Choose an installer and complete guided setup.','product.install':'View downloads',
    'tech.eyebrow':'VISIBILITY · INVESTIGATION · RESPONSE','tech.title':'A technical flow from signal to decision.','tech.body':'CISPAR organizes activity in your environment so every step can be reviewed and operated with context.','tech.detect':'Detect','tech.detectBody':'Receive, normalize, and prioritize security activity.','tech.investigate':'Investigate','tech.investigateBody':'Connect evidence and events to provide incident context.','tech.respond':'Respond','tech.respondBody':'Run defined playbooks and retain traceability.','tech.terminal':'CISPAR / incident-response','tech.live':'RUNNING','tech.line1':'[ingestion] security events received','tech.line2':'[analysis] authentication context prepared','tech.line3':'[playbook] review required before containment','tech.line4':'[record] incident documented',
    'download.eyebrow':'DOWNLOADS','download.title':'Install CISPAR in your environment.','download.body':'Choose your platform. Every published release includes SHA-256 to verify the download.','download.recommended':'RECOMMENDED FOR THIS DEVICE','download.pending':'Upcoming release','download.checksum':'Pending publication','download.button':'Installer in preparation','download.after':'AFTER DOWNLOADING','download.afterTitle':'The installer prepares Docker and opens local setup.','download.step1':'Run the installer for your operating system.','download.step2':'Sign in when CISPAR asks for authorization.','download.step3':'Complete guided setup in your browser.','download.help':'Need help with architecture, requirements, or an enterprise installation?','download.contact':'Contact the team',
    'pricing.eyebrow':'PLANS','pricing.title':'Choose the scope for your operation.','pricing.body':'Pricing and limits depend on your environment, sources, and deployment requirements.','pricing.starter':'Starter','pricing.starterBody':'To validate CISPAR in an initial environment.','pricing.enterprise':'Enterprise','pricing.enterpriseBody':'For teams with larger volume, integrations, or deployment requirements.','pricing.quote':'Custom proposal','pricing.access':'Request access','pricing.sales':'Talk to sales','pricing.note':'For multiple sites, integrations, or specific requirements, tell us about your environment.',
    'contact.eyebrow':'CONTACT','contact.title':'Let’s talk about your environment.','contact.body':'Request a demo, proposal, or help planning installation.','contact.tipTitle':'For a better response','contact.tip':'Include your environment type, estimated sources, and integration needs.','contact.type':'Request type','contact.name':'Name','contact.company':'Company','contact.email':'Work email','contact.environment':'Environment','contact.message':'What do you need?','contact.placeholder':'Briefly describe your environment and goals.','contact.send':'Prepare request','contact.sent':'Your email client opened with the request prepared. If it did not open, write to sales@cispar.io.','contact.demo':'Demo','contact.quote':'Quote','contact.install':'Installation','footer.tagline':'Security operations installed in your environment.'
  }
};
const I18nContext = createContext<I18nValue>({ locale: 'es', setLocale: () => undefined, t: (key) => key });
export function I18nProvider({ children }: { readonly children: React.ReactNode }): React.ReactElement { const [locale, setLocaleState] = useState<Locale>(() => (localStorage.getItem('cispar-locale') as Locale) || 'es'); const setLocale = (next: Locale): void => { localStorage.setItem('cispar-locale', next); setLocaleState(next); }; useEffect(() => { document.documentElement.lang = locale; }, [locale]); return <I18nContext.Provider value={{ locale, setLocale, t: (key) => copy[locale][key] ?? copy.es[key] ?? key }}>{children}</I18nContext.Provider>; }
export function useI18n(): I18nValue { return useContext(I18nContext); }
