import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { detectPlatform, releaseCatalog, type Release } from '../lib/releases';

const osLabels = { macos: 'macOS', windows: 'Windows', linux: 'Linux' } as const;
export function DownloadPage(): React.ReactElement {
  const [recommended, setRecommended] = useState<string | null>(null);
  useEffect(() => { const platform = detectPlatform(); if (platform) setRecommended(`${platform.os}-${platform.arch}`); }, []);
  const handleDownload = (release: Release): void => { if (release.url) window.location.assign(release.url); };
  return <section className="page"><div className="section-container"><div className="page-heading"><p className="eyebrow">DESCARGAS</p><h1>Instala CISPAR en tu entorno.</h1><p>Selecciona tu plataforma. Cada release publicada incluye su suma SHA-256 para verificar la descarga antes de instalarla.</p></div><div className="download-grid">{releaseCatalog.map((release) => { const isRecommended = recommended === `${release.os}-${release.arch}`; return <article className={`release-card ${isRecommended ? 'recommended' : ''}`} key={release.id}>{isRecommended && <p className="recommendation">RECOMENDADO PARA ESTE EQUIPO</p>}<p className="release-os">{osLabels[release.os]}</p><h2>{release.label.replace(`${osLabels[release.os]} · `, '')}</h2><p>{release.requirements}</p><div className="release-meta"><span>{release.version ? `Versión ${release.version}` : 'Próxima release'}</span><span>{release.sha256 ? 'SHA-256 disponible' : 'Pendiente de publicación'}</span></div><button className={release.available ? 'btn-primary' : 'btn-disabled'} disabled={!release.available} onClick={() => handleDownload(release)}>{release.available ? 'Descargar instalador' : 'Instalador en preparación'}</button></article>; })}</div><div className="download-help"><div><p className="eyebrow">DESPUÉS DE DESCARGAR</p><h2>El instalador prepara Docker y abre la configuración local.</h2><ol><li>Ejecuta el instalador correspondiente a tu sistema.</li><li>Inicia sesión cuando CISPAR solicite autorización.</li><li>Completa la configuración guiada en tu navegador.</li></ol></div><div className="help-actions"><p>¿Necesitas ayuda con arquitectura, requisitos o una instalación empresarial?</p><Link className="btn-secondary" to="/contact">Contactar al equipo</Link></div></div></div></section>;
}
